CREATE TYPE "WorkspaceMemberRole" AS ENUM ('OWNER','ADMIN','MEMBER','VIEWER');
CREATE TYPE "DocumentStatus" AS ENUM ('UPLOADING','READY');
CREATE TYPE "ProcessingStatus" AS ENUM ('QUEUED','VALIDATING','ANALYZING','FINALIZING','COMPLETED','FAILED','CANCELED');
CREATE TYPE "QueueOutboxStatus" AS ENUM ('PENDING','CLAIMED','PUBLISHED','FAILED');
CREATE TYPE "ArtifactKind" AS ENUM ('SOURCE','RESULT');
CREATE TYPE "WebhookDeliveryStatus" AS ENUM ('PENDING','SUCCEEDED','FAILED');

CREATE TABLE "Workspace" ("id" TEXT NOT NULL,"name" TEXT NOT NULL,"slug" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Workspace_pkey" PRIMARY KEY ("id"));
CREATE TABLE "User" ("id" TEXT NOT NULL,"email" TEXT NOT NULL,"passwordHash" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "User_pkey" PRIMARY KEY ("id"));
CREATE TABLE "WorkspaceMember" ("workspaceId" TEXT NOT NULL,"userId" TEXT NOT NULL,"role" "WorkspaceMemberRole" NOT NULL DEFAULT 'MEMBER',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "WorkspaceMember_pkey" PRIMARY KEY ("workspaceId","userId"));
CREATE TABLE "Session" ("id" TEXT NOT NULL,"userId" TEXT NOT NULL,"tokenHash" TEXT NOT NULL,"expiresAt" TIMESTAMP(3) NOT NULL,"revokedAt" TIMESTAMP(3),"userAgent" TEXT,"ipAddress" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Session_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ApiKey" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"userId" TEXT NOT NULL,"name" TEXT NOT NULL,"secretHash" TEXT NOT NULL,"scopes" JSONB NOT NULL,"expiresAt" TIMESTAMP(3),"revokedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"lastUsedAt" TIMESTAMP(3),CONSTRAINT "ApiKey_pkey" PRIMARY KEY ("id"));
CREATE TABLE "Document" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"title" TEXT NOT NULL,"contentType" TEXT NOT NULL,"byteSize" INTEGER NOT NULL,"status" "DocumentStatus" NOT NULL DEFAULT 'UPLOADING',"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "Document_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProcessingRun" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"documentId" TEXT NOT NULL,"revision" INTEGER NOT NULL,"status" "ProcessingStatus" NOT NULL DEFAULT 'QUEUED',"stageRevision" INTEGER NOT NULL DEFAULT 1,"leaseExpiresAt" TIMESTAMP(3),"errorCode" TEXT,"result" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL,CONSTRAINT "ProcessingRun_pkey" PRIMARY KEY ("id"));
CREATE TABLE "ProcessingAttempt" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"processingRunId" TEXT NOT NULL,"stage" TEXT NOT NULL,"attemptNumber" INTEGER NOT NULL,"status" TEXT NOT NULL,"startedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"finishedAt" TIMESTAMP(3),"error" JSONB,CONSTRAINT "ProcessingAttempt_pkey" PRIMARY KEY ("id"));
CREATE TABLE "DocumentArtifact" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"documentId" TEXT NOT NULL,"processingRunId" TEXT,"kind" "ArtifactKind" NOT NULL,"objectKey" TEXT NOT NULL,"contentType" TEXT NOT NULL,"byteSize" INTEGER NOT NULL,"checksum" TEXT,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "DocumentArtifact_pkey" PRIMARY KEY ("id"));
CREATE TABLE "WebhookEndpoint" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"url" TEXT NOT NULL,"secretHash" TEXT NOT NULL,"events" JSONB NOT NULL,"active" BOOLEAN NOT NULL DEFAULT true,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "WebhookEndpoint_pkey" PRIMARY KEY ("id"));
CREATE TABLE "WebhookDelivery" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"endpointId" TEXT NOT NULL,"eventId" TEXT NOT NULL,"requestBody" BYTEA NOT NULL,"signatureInput" TEXT NOT NULL,"status" "WebhookDeliveryStatus" NOT NULL DEFAULT 'PENDING',"attempts" INTEGER NOT NULL DEFAULT 0,"nextAttemptAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "WebhookDelivery_pkey" PRIMARY KEY ("id"));
CREATE TABLE "AuditLog" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"principalId" TEXT NOT NULL,"action" TEXT NOT NULL,"resourceType" TEXT NOT NULL,"resourceId" TEXT,"metadata" JSONB,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "AuditLog_pkey" PRIMARY KEY ("id"));
CREATE TABLE "IdempotencyRecord" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"principalId" TEXT NOT NULL,"operation" TEXT NOT NULL,"key" TEXT NOT NULL,"requestHash" TEXT NOT NULL,"response" JSONB NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"expiresAt" TIMESTAMP(3),CONSTRAINT "IdempotencyRecord_pkey" PRIMARY KEY ("id"));
CREATE TABLE "QueueOutbox" ("id" TEXT NOT NULL,"workspaceId" TEXT NOT NULL,"contract" TEXT NOT NULL,"businessId" TEXT NOT NULL,"revision" INTEGER NOT NULL,"payload" JSONB NOT NULL,"status" "QueueOutboxStatus" NOT NULL DEFAULT 'PENDING',"availableAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,"claimedAt" TIMESTAMP(3),"publishedAt" TIMESTAMP(3),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "QueueOutbox_pkey" PRIMARY KEY ("id"));

CREATE UNIQUE INDEX "Workspace_slug_key" ON "Workspace"("slug"); CREATE UNIQUE INDEX "User_email_key" ON "User"("email"); CREATE UNIQUE INDEX "Session_tokenHash_key" ON "Session"("tokenHash"); CREATE UNIQUE INDEX "ApiKey_secretHash_key" ON "ApiKey"("secretHash");
CREATE UNIQUE INDEX "Document_workspaceId_id_key" ON "Document"("workspaceId","id"); CREATE UNIQUE INDEX "ProcessingRun_workspaceId_id_key" ON "ProcessingRun"("workspaceId","id"); CREATE UNIQUE INDEX "ProcessingRun_workspaceId_documentId_revision_key" ON "ProcessingRun"("workspaceId","documentId","revision");
CREATE UNIQUE INDEX "ProcessingAttempt_workspaceId_id_key" ON "ProcessingAttempt"("workspaceId","id"); CREATE UNIQUE INDEX "ProcessingAttempt_identity_key" ON "ProcessingAttempt"("workspaceId","processingRunId","stage","attemptNumber"); CREATE UNIQUE INDEX "DocumentArtifact_workspaceId_id_key" ON "DocumentArtifact"("workspaceId","id"); CREATE UNIQUE INDEX "DocumentArtifact_workspaceId_objectKey_key" ON "DocumentArtifact"("workspaceId","objectKey");
CREATE UNIQUE INDEX "WebhookEndpoint_workspaceId_id_key" ON "WebhookEndpoint"("workspaceId","id"); CREATE UNIQUE INDEX "WebhookEndpoint_workspaceId_url_key" ON "WebhookEndpoint"("workspaceId","url"); CREATE UNIQUE INDEX "WebhookDelivery_workspaceId_id_key" ON "WebhookDelivery"("workspaceId","id"); CREATE UNIQUE INDEX "WebhookDelivery_identity_key" ON "WebhookDelivery"("workspaceId","endpointId","eventId"); CREATE UNIQUE INDEX "AuditLog_workspaceId_id_key" ON "AuditLog"("workspaceId","id"); CREATE UNIQUE INDEX "IdempotencyRecord_identity_key" ON "IdempotencyRecord"("workspaceId","operation","key"); CREATE UNIQUE INDEX "QueueOutbox_workspaceId_id_key" ON "QueueOutbox"("workspaceId","id"); CREATE UNIQUE INDEX "QueueOutbox_identity_key" ON "QueueOutbox"("workspaceId","contract","businessId","revision");

ALTER TABLE "WorkspaceMember" ADD CONSTRAINT "WorkspaceMember_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "WorkspaceMember" ADD CONSTRAINT "WorkspaceMember_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Session" ADD CONSTRAINT "Session_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ApiKey" ADD CONSTRAINT "ApiKey_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ApiKey" ADD CONSTRAINT "ApiKey_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "Document" ADD CONSTRAINT "Document_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ProcessingRun" ADD CONSTRAINT "ProcessingRun_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "ProcessingRun" ADD CONSTRAINT "ProcessingRun_document_fkey" FOREIGN KEY ("workspaceId","documentId") REFERENCES "Document"("workspaceId","id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "ProcessingAttempt" ADD CONSTRAINT "ProcessingAttempt_run_fkey" FOREIGN KEY ("workspaceId","processingRunId") REFERENCES "ProcessingRun"("workspaceId","id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "DocumentArtifact" ADD CONSTRAINT "DocumentArtifact_workspace_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "DocumentArtifact" ADD CONSTRAINT "DocumentArtifact_document_fkey" FOREIGN KEY ("workspaceId","documentId") REFERENCES "Document"("workspaceId","id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "DocumentArtifact" ADD CONSTRAINT "DocumentArtifact_run_fkey" FOREIGN KEY ("workspaceId","processingRunId") REFERENCES "ProcessingRun"("workspaceId","id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "WebhookEndpoint" ADD CONSTRAINT "WebhookEndpoint_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "WebhookDelivery" ADD CONSTRAINT "WebhookDelivery_endpoint_fkey" FOREIGN KEY ("workspaceId","endpointId") REFERENCES "WebhookEndpoint"("workspaceId","id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "AuditLog" ADD CONSTRAINT "AuditLog_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "IdempotencyRecord" ADD CONSTRAINT "IdempotencyRecord_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE; ALTER TABLE "QueueOutbox" ADD CONSTRAINT "QueueOutbox_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE CASCADE ON UPDATE CASCADE;
