FROM oven/bun:1.3.14-alpine
WORKDIR /app
COPY package.json bun.lock ./
COPY apps/worker/package.json apps/worker/package.json
COPY packages/config/package.json packages/config/package.json
COPY packages/queue/package.json packages/queue/package.json
COPY packages/typescript-config/package.json packages/typescript-config/package.json
RUN bun install --frozen-lockfile --ignore-scripts --filter @repo/worker
COPY apps/worker apps/worker
COPY packages/config packages/config
COPY packages/queue packages/queue
COPY config /app/config
CMD ["bun", "run", "apps/worker/src/main.ts"]
