FROM oven/bun:1.3.14-alpine
WORKDIR /app
COPY package.json bun.lock ./
COPY apps/migrate/package.json apps/migrate/package.json
COPY packages/db/package.json packages/db/package.json
COPY packages/typescript-config/package.json packages/typescript-config/package.json
RUN bun install --ignore-scripts --filter @repo/migrate
COPY apps/migrate apps/migrate
COPY packages/db packages/db
COPY config /app/config
RUN bun install --ignore-scripts --filter @repo/db
CMD ["bun", "run", "apps/migrate/src/main.ts"]
