FROM oven/bun:1.4.2-alpine
WORKDIR /app
COPY package.json bun.lock ./
COPY apps apps
COPY packages packages
RUN bun install --ignore-scripts
RUN bun run --cwd packages/db db:generate
COPY config /app/config
CMD ["bun", "run", "packages/config/src/run.ts", "--modules", "base,worker,storage", "--", "bun", "apps/worker/src/main.ts"]
