FROM oven/bun:1.3.14-alpine
WORKDIR /app
COPY package.json bun.lock ./
COPY apps apps
COPY packages packages
COPY config config
RUN bun install --ignore-scripts
RUN bun run --cwd packages/database db:generate
EXPOSE 4101
CMD ["bun", "run", "packages/config/src/run.ts", "--modules", "base,api,storage", "--", "bun", "apps/api/src/server.ts"]
