FROM oven/bun:1.4.2-alpine
WORKDIR /app
COPY package.json bun.lock ./
COPY apps apps
COPY packages packages
RUN bun install --ignore-scripts
RUN DATABASE_URL=postgresql://tooling:tooling@localhost:5432/tooling bun --no-env-file run --cwd packages/db db:generate
COPY config /app/config
CMD ["bun", "--no-env-file", "run", "packages/config/src/run.ts", "--runtime", "worker", "--root", "/app", "--", "bun", "apps/worker/src/main.ts"]
