/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as ApiSplatRouteImport } from './app/api/$'
import { Route as HealthIndexRouteImport } from './app/health/index'

const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/api/$': typeof ApiSplatRoute
  '/health/': typeof HealthIndexRoute
}
export interface FileRoutesByTo {
  '/api/$': typeof ApiSplatRoute
  '/health': typeof HealthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/api/$': typeof ApiSplatRoute
  '/health/': typeof HealthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/api/$' | '/health/'
  fileRoutesByTo: FileRoutesByTo
  to: '/api/$' | '/health'
  id: '__root__' | '/api/$' | '/health/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ApiSplatRoute: typeof ApiSplatRoute
  HealthIndexRoute: typeof HealthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  ApiSplatRoute: ApiSplatRoute,
  HealthIndexRoute: HealthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
