/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AuthenticatedRouteRouteImport } from './app/_authenticated/route'
import { Route as PublicRouteRouteImport } from './app/_public/route'
import { Route as AuthenticatedAppRouteRouteImport } from './app/_authenticated/app/route'
import { Route as PublicIndexRouteImport } from './app/_public/index'
import { Route as HealthIndexRouteImport } from './app/health/index'
import { Route as TrpcSplatRouteImport } from './app/trpc/$'
import { Route as PublicRegisterIndexRouteImport } from './app/_public/register/index'
import { Route as PublicSignInIndexRouteImport } from './app/_public/sign-in/index'
import { Route as AuthenticatedAppActivityIndexRouteImport } from './app/_authenticated/app/activity/index'
import { Route as AuthenticatedAppDocumentsIndexRouteImport } from './app/_authenticated/app/documents/index'
import { Route as AuthenticatedAppOverviewIndexRouteImport } from './app/_authenticated/app/overview/index'
import { Route as AuthenticatedAppDevelopersApiKeysIndexRouteImport } from './app/_authenticated/app/developers/api-keys/index'
import { Route as AuthenticatedAppDevelopersWebhooksIndexRouteImport } from './app/_authenticated/app/developers/webhooks/index'
import { Route as AuthenticatedAppDocumentsDocumentIdIndexRouteImport } from './app/_authenticated/app/documents/$documentId/index'
import { Route as AuthenticatedAppDocumentsNewIndexRouteImport } from './app/_authenticated/app/documents/new/index'
import { Route as AuthenticatedAppSettingsMembersIndexRouteImport } from './app/_authenticated/app/settings/members/index'
import { Route as AuthenticatedAppSettingsWorkspaceIndexRouteImport } from './app/_authenticated/app/settings/workspace/index'
import { Route as AuthenticatedAppDocumentsDocumentIdRunsRunIdIndexRouteImport } from './app/_authenticated/app/documents/$documentId/runs/$runId/index'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAppRouteRoute = AuthenticatedAppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const HealthIndexRoute = HealthIndexRouteImport.update({
  id: '/health/',
  path: '/health/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrpcSplatRoute = TrpcSplatRouteImport.update({
  id: '/trpc/$',
  path: '/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRegisterIndexRoute = PublicRegisterIndexRouteImport.update({
  id: '/register/',
  path: '/register/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSignInIndexRoute = PublicSignInIndexRouteImport.update({
  id: '/sign-in/',
  path: '/sign-in/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AuthenticatedAppActivityIndexRoute =
  AuthenticatedAppActivityIndexRouteImport.update({
    id: '/activity/',
    path: '/activity/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDocumentsIndexRoute =
  AuthenticatedAppDocumentsIndexRouteImport.update({
    id: '/documents/',
    path: '/documents/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppOverviewIndexRoute =
  AuthenticatedAppOverviewIndexRouteImport.update({
    id: '/overview/',
    path: '/overview/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDevelopersApiKeysIndexRoute =
  AuthenticatedAppDevelopersApiKeysIndexRouteImport.update({
    id: '/developers/api-keys/',
    path: '/developers/api-keys/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDevelopersWebhooksIndexRoute =
  AuthenticatedAppDevelopersWebhooksIndexRouteImport.update({
    id: '/developers/webhooks/',
    path: '/developers/webhooks/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDocumentsDocumentIdIndexRoute =
  AuthenticatedAppDocumentsDocumentIdIndexRouteImport.update({
    id: '/documents/$documentId/',
    path: '/documents/$documentId/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDocumentsNewIndexRoute =
  AuthenticatedAppDocumentsNewIndexRouteImport.update({
    id: '/documents/new/',
    path: '/documents/new/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsMembersIndexRoute =
  AuthenticatedAppSettingsMembersIndexRouteImport.update({
    id: '/settings/members/',
    path: '/settings/members/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppSettingsWorkspaceIndexRoute =
  AuthenticatedAppSettingsWorkspaceIndexRouteImport.update({
    id: '/settings/workspace/',
    path: '/settings/workspace/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)
const AuthenticatedAppDocumentsDocumentIdRunsRunIdIndexRoute =
  AuthenticatedAppDocumentsDocumentIdRunsRunIdIndexRouteImport.update({
    id: '/documents/$documentId/runs/$runId/',
    path: '/documents/$documentId/runs/$runId/',
    getParentRoute: () => AuthenticatedAppRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/trpc/$': typeof TrpcSplatRoute
  '/health/': typeof HealthIndexRoute
  '/register/': typeof PublicRegisterIndexRoute
  '/sign-in/': typeof PublicSignInIndexRoute
  '/app/activity/': typeof AuthenticatedAppActivityIndexRoute
  '/app/documents/': typeof AuthenticatedAppDocumentsIndexRoute
  '/app/overview/': typeof AuthenticatedAppOverviewIndexRoute
  '/app/developers/api-keys/': typeof AuthenticatedAppDevelopersApiKeysIndexRoute
  '/app/developers/webhooks/': typeof AuthenticatedAppDevelopersWebhooksIndexRoute
  '/app/documents/$documentId/': typeof AuthenticatedAppDocumentsDocumentIdIndexRoute
  '/app/documents/new/': typeof AuthenticatedAppDocumentsNewIndexRoute
  '/app/settings/members/': typeof AuthenticatedAppSettingsMembersIndexRoute
  '/app/settings/workspace/': typeof AuthenticatedAppSettingsWorkspaceIndexRoute
  '/app/documents/$documentId/runs/$runId/': typeof AuthenticatedAppDocumentsDocumentIdRunsRunIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof PublicIndexRoute
  '/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/trpc/$': typeof TrpcSplatRoute
  '/health': typeof HealthIndexRoute
  '/register': typeof PublicRegisterIndexRoute
  '/sign-in': typeof PublicSignInIndexRoute
  '/app/activity': typeof AuthenticatedAppActivityIndexRoute
  '/app/documents': typeof AuthenticatedAppDocumentsIndexRoute
  '/app/overview': typeof AuthenticatedAppOverviewIndexRoute
  '/app/developers/api-keys': typeof AuthenticatedAppDevelopersApiKeysIndexRoute
  '/app/developers/webhooks': typeof AuthenticatedAppDevelopersWebhooksIndexRoute
  '/app/documents/$documentId': typeof AuthenticatedAppDocumentsDocumentIdIndexRoute
  '/app/documents/new': typeof AuthenticatedAppDocumentsNewIndexRoute
  '/app/settings/members': typeof AuthenticatedAppSettingsMembersIndexRoute
  '/app/settings/workspace': typeof AuthenticatedAppSettingsWorkspaceIndexRoute
  '/app/documents/$documentId/runs/$runId': typeof AuthenticatedAppDocumentsDocumentIdRunsRunIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_public': typeof PublicRouteRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteRouteWithChildren
  '/trpc/$': typeof TrpcSplatRoute
  '/_public/': typeof PublicIndexRoute
  '/health/': typeof HealthIndexRoute
  '/_public/register/': typeof PublicRegisterIndexRoute
  '/_public/sign-in/': typeof PublicSignInIndexRoute
  '/_authenticated/app/activity/': typeof AuthenticatedAppActivityIndexRoute
  '/_authenticated/app/documents/': typeof AuthenticatedAppDocumentsIndexRoute
  '/_authenticated/app/overview/': typeof AuthenticatedAppOverviewIndexRoute
  '/_authenticated/app/developers/api-keys/': typeof AuthenticatedAppDevelopersApiKeysIndexRoute
  '/_authenticated/app/developers/webhooks/': typeof AuthenticatedAppDevelopersWebhooksIndexRoute
  '/_authenticated/app/documents/$documentId/': typeof AuthenticatedAppDocumentsDocumentIdIndexRoute
  '/_authenticated/app/documents/new/': typeof AuthenticatedAppDocumentsNewIndexRoute
  '/_authenticated/app/settings/members/': typeof AuthenticatedAppSettingsMembersIndexRoute
  '/_authenticated/app/settings/workspace/': typeof AuthenticatedAppSettingsWorkspaceIndexRoute
  '/_authenticated/app/documents/$documentId/runs/$runId/': typeof AuthenticatedAppDocumentsDocumentIdRunsRunIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/trpc/$'
    | '/health/'
    | '/register/'
    | '/sign-in/'
    | '/app/activity/'
    | '/app/documents/'
    | '/app/overview/'
    | '/app/developers/api-keys/'
    | '/app/developers/webhooks/'
    | '/app/documents/$documentId/'
    | '/app/documents/new/'
    | '/app/settings/members/'
    | '/app/settings/workspace/'
    | '/app/documents/$documentId/runs/$runId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/trpc/$'
    | '/health'
    | '/register'
    | '/sign-in'
    | '/app/activity'
    | '/app/documents'
    | '/app/overview'
    | '/app/developers/api-keys'
    | '/app/developers/webhooks'
    | '/app/documents/$documentId'
    | '/app/documents/new'
    | '/app/settings/members'
    | '/app/settings/workspace'
    | '/app/documents/$documentId/runs/$runId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/_authenticated/app'
    | '/trpc/$'
    | '/_public/'
    | '/health/'
    | '/_public/register/'
    | '/_public/sign-in/'
    | '/_authenticated/app/activity/'
    | '/_authenticated/app/documents/'
    | '/_authenticated/app/overview/'
    | '/_authenticated/app/developers/api-keys/'
    | '/_authenticated/app/developers/webhooks/'
    | '/_authenticated/app/documents/$documentId/'
    | '/_authenticated/app/documents/new/'
    | '/_authenticated/app/settings/members/'
    | '/_authenticated/app/settings/workspace/'
    | '/_authenticated/app/documents/$documentId/runs/$runId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  TrpcSplatRoute: typeof TrpcSplatRoute
  HealthIndexRoute: typeof HealthIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/health/': {
      id: '/health/'
      path: '/health'
      fullPath: '/health/'
      preLoaderRoute: typeof HealthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trpc/$': {
      id: '/trpc/$'
      path: '/trpc/$'
      fullPath: '/trpc/$'
      preLoaderRoute: typeof TrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/register/': {
      id: '/_public/register/'
      path: '/register'
      fullPath: '/register/'
      preLoaderRoute: typeof PublicRegisterIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/sign-in/': {
      id: '/_public/sign-in/'
      path: '/sign-in'
      fullPath: '/sign-in/'
      preLoaderRoute: typeof PublicSignInIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_authenticated/app/activity/': {
      id: '/_authenticated/app/activity/'
      path: '/activity'
      fullPath: '/app/activity/'
      preLoaderRoute: typeof AuthenticatedAppActivityIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/documents/': {
      id: '/_authenticated/app/documents/'
      path: '/documents'
      fullPath: '/app/documents/'
      preLoaderRoute: typeof AuthenticatedAppDocumentsIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/overview/': {
      id: '/_authenticated/app/overview/'
      path: '/overview'
      fullPath: '/app/overview/'
      preLoaderRoute: typeof AuthenticatedAppOverviewIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/developers/api-keys/': {
      id: '/_authenticated/app/developers/api-keys/'
      path: '/developers/api-keys'
      fullPath: '/app/developers/api-keys/'
      preLoaderRoute: typeof AuthenticatedAppDevelopersApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/developers/webhooks/': {
      id: '/_authenticated/app/developers/webhooks/'
      path: '/developers/webhooks'
      fullPath: '/app/developers/webhooks/'
      preLoaderRoute: typeof AuthenticatedAppDevelopersWebhooksIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/documents/$documentId/': {
      id: '/_authenticated/app/documents/$documentId/'
      path: '/documents/$documentId'
      fullPath: '/app/documents/$documentId/'
      preLoaderRoute: typeof AuthenticatedAppDocumentsDocumentIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/documents/new/': {
      id: '/_authenticated/app/documents/new/'
      path: '/documents/new'
      fullPath: '/app/documents/new/'
      preLoaderRoute: typeof AuthenticatedAppDocumentsNewIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings/members/': {
      id: '/_authenticated/app/settings/members/'
      path: '/settings/members'
      fullPath: '/app/settings/members/'
      preLoaderRoute: typeof AuthenticatedAppSettingsMembersIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/settings/workspace/': {
      id: '/_authenticated/app/settings/workspace/'
      path: '/settings/workspace'
      fullPath: '/app/settings/workspace/'
      preLoaderRoute: typeof AuthenticatedAppSettingsWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
    '/_authenticated/app/documents/$documentId/runs/$runId/': {
      id: '/_authenticated/app/documents/$documentId/runs/$runId/'
      path: '/documents/$documentId/runs/$runId'
      fullPath: '/app/documents/$documentId/runs/$runId/'
      preLoaderRoute: typeof AuthenticatedAppDocumentsDocumentIdRunsRunIdIndexRouteImport
      parentRoute: typeof AuthenticatedAppRouteRoute
    }
  }
}

interface AuthenticatedAppRouteRouteChildren {
  AuthenticatedAppActivityIndexRoute: typeof AuthenticatedAppActivityIndexRoute
  AuthenticatedAppDocumentsIndexRoute: typeof AuthenticatedAppDocumentsIndexRoute
  AuthenticatedAppOverviewIndexRoute: typeof AuthenticatedAppOverviewIndexRoute
  AuthenticatedAppDevelopersApiKeysIndexRoute: typeof AuthenticatedAppDevelopersApiKeysIndexRoute
  AuthenticatedAppDevelopersWebhooksIndexRoute: typeof AuthenticatedAppDevelopersWebhooksIndexRoute
  AuthenticatedAppDocumentsDocumentIdIndexRoute: typeof AuthenticatedAppDocumentsDocumentIdIndexRoute
  AuthenticatedAppDocumentsNewIndexRoute: typeof AuthenticatedAppDocumentsNewIndexRoute
  AuthenticatedAppSettingsMembersIndexRoute: typeof AuthenticatedAppSettingsMembersIndexRoute
  AuthenticatedAppSettingsWorkspaceIndexRoute: typeof AuthenticatedAppSettingsWorkspaceIndexRoute
  AuthenticatedAppDocumentsDocumentIdRunsRunIdIndexRoute: typeof AuthenticatedAppDocumentsDocumentIdRunsRunIdIndexRoute
}

const AuthenticatedAppRouteRouteChildren: AuthenticatedAppRouteRouteChildren = {
  AuthenticatedAppActivityIndexRoute: AuthenticatedAppActivityIndexRoute,
  AuthenticatedAppDocumentsIndexRoute: AuthenticatedAppDocumentsIndexRoute,
  AuthenticatedAppOverviewIndexRoute: AuthenticatedAppOverviewIndexRoute,
  AuthenticatedAppDevelopersApiKeysIndexRoute:
    AuthenticatedAppDevelopersApiKeysIndexRoute,
  AuthenticatedAppDevelopersWebhooksIndexRoute:
    AuthenticatedAppDevelopersWebhooksIndexRoute,
  AuthenticatedAppDocumentsDocumentIdIndexRoute:
    AuthenticatedAppDocumentsDocumentIdIndexRoute,
  AuthenticatedAppDocumentsNewIndexRoute:
    AuthenticatedAppDocumentsNewIndexRoute,
  AuthenticatedAppSettingsMembersIndexRoute:
    AuthenticatedAppSettingsMembersIndexRoute,
  AuthenticatedAppSettingsWorkspaceIndexRoute:
    AuthenticatedAppSettingsWorkspaceIndexRoute,
  AuthenticatedAppDocumentsDocumentIdRunsRunIdIndexRoute:
    AuthenticatedAppDocumentsDocumentIdRunsRunIdIndexRoute,
}

const AuthenticatedAppRouteRouteWithChildren =
  AuthenticatedAppRouteRoute._addFileChildren(
    AuthenticatedAppRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAppRouteRoute: typeof AuthenticatedAppRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAppRouteRoute: AuthenticatedAppRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PublicRouteRouteChildren {
  PublicIndexRoute: typeof PublicIndexRoute
  PublicRegisterIndexRoute: typeof PublicRegisterIndexRoute
  PublicSignInIndexRoute: typeof PublicSignInIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicIndexRoute: PublicIndexRoute,
  PublicRegisterIndexRoute: PublicRegisterIndexRoute,
  PublicSignInIndexRoute: PublicSignInIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  PublicRouteRoute: PublicRouteRouteWithChildren,
  TrpcSplatRoute: TrpcSplatRoute,
  HealthIndexRoute: HealthIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
